// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VBtn: typeof import('./../app/components/VBtn.vue')['default']
    VCard: typeof import('./../app/components/VCard.vue')['default']
    VCardContent: typeof import('./../app/components/VCardContent.vue')['default']
    VCardHead: typeof import('./../app/components/VCardHead.vue')['default']
    VCardTitle: typeof import('./../app/components/VCardTitle.vue')['default']
    VChart: typeof import('./../app/components/VChart.vue')['default']
    VCheckbox: typeof import('./../app/components/VCheckbox.vue')['default']
    VCode: typeof import('./../app/components/VCode.vue')['default']
    VContainer: typeof import('./../app/components/VContainer.vue')['default']
    VDialog: typeof import('./../app/components/VDialog.vue')['default']
    VDivider: typeof import('./../app/components/VDivider.vue')['default']
    VDrawer: typeof import('./../app/components/VDrawer.vue')['default']
    VForm: typeof import('./../app/components/VForm.vue')['default']
    VGallery: typeof import('./../app/components/VGallery.vue')['default']
    VIcon: typeof import('./../app/components/VIcon.vue')['default']
    VIconPicker: typeof import('./../app/components/VIconPicker.vue')['default']
    VInput: typeof import('./../app/components/VInput.vue')['default']
    VLayout: typeof import('./../app/components/VLayout.vue')['default']
    VLayoutContent: typeof import('./../app/components/VLayoutContent.vue')['default']
    VLayoutDrawer: typeof import('./../app/components/VLayoutDrawer.vue')['default']
    VLayoutToolbar: typeof import('./../app/components/VLayoutToolbar.vue')['default']
    VLink: typeof import('./../app/components/VLink.vue')['default']
    VListItem: typeof import('./../app/components/VListItem.vue')['default']
    VLogo: typeof import('./../app/components/VLogo.vue')['default']
    VMenu: typeof import('./../app/components/VMenu.vue')['default']
    VResizeLine: typeof import('./../app/components/VResizeLine.vue')['default']
    VSelect: typeof import('./../app/components/VSelect.vue')['default']
    VTab: typeof import('./../app/components/VTab.vue')['default']
    VTabItem: typeof import('./../app/components/VTabItem.vue')['default']
    VTable: typeof import('./../app/components/VTable.vue')['default']
    VTd: typeof import('./../app/components/VTd.vue')['default']
    VTextarea: typeof import('./../app/components/VTextarea.vue')['default']
    VTh: typeof import('./../app/components/VTh.vue')['default']
    VTr: typeof import('./../app/components/VTr.vue')['default']
  }
}
